# Generated by Django 4.0.1 on 2022-01-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rscript',
            old_name='df_name',
            new_name='df',
        ),
    ]
