version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn pythonwithr.wsgi:application -w 2 -b :8000
